backend:
  name: git-gateway
  branch: main

media_folder: images/uploads
public_folder: /images/uploads

collections:
  - name: "home_page"
    label: "Home Page"
    delete: false
    editor:
      preview: false
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/hero.json"
        fields:
          - { label: "Hero Line 1", name: "line1", widget: "string" }
          - { label: "Hero Line 2", name: "line2", widget: "string" }
          - { label: "Hero Description", name: "description", widget: "text" }
